version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - STRAPI_APP_NAME=${STRAPI_APP_NAME}
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/strapi/
