version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    # environment:
    #   - POSTGRES_USER=test
    #   - POSTGRES_PASSWORD=test
    #   - POSTGRES_DB=test
